# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 
# Created on: 2018-08-02 11:14:21.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: bf <Folder> 
# Description: From a input folder it take all shape files and generate a merge.shp in the same folder.
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
# Script arguments
Folder = arcpy.GetParameterAsText(0)
#Outfolder=arcpy.GetParameterAsT

# Local variables:

merge=""
for root, dirs, files in os.walk(Folder):
    for file in files:
        if file.endswith(".shp"):
             merge=merge+os.path.join(root, file)+";"
arcpy.Merge_management(merge[:-1],os.path.join(Folder,"merge.shp"))
